//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/fy_infernos.html
halflife.wad
sound/ambience/wind2.wav
cstrike.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
models/pi_fern.mdl
models/pi_stlamp.mdl
chateau.wad
de_airstrip.wad
cs_havana.wad
models/bag.mdl
models/lv_bottle.mdl
maps/fy_infernos.bsp
maps/fy_infernos.txt
